config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books
         has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

        before_action :find_book, only: [:show, :edit, :update, :destroy]

        # will redirect to the index view by default
        # render '' indicates what page to show
        # redirect_to : indicates root

    def index
            if params[:category].blank?
                @books = Book.all.order("created_at DESC")
            else
                @category_id = Category.find_by(name: params[:category]).id
                @books = Book.where(:category_id => @category_id).order("created_at DESC")
            end
    end

    def show 
        if @book.reviews.blank?
            @average_review = 0
        else
            @average_review = @book.reviews.average(:rating).round(2)
        end
    end

    def new
        @book = current_user.books.build
        @categories = Category.all.map{ |c| [ c.name, c.id ]  }
        #@book = Book.new
    end

    def create
        #@book = Book.new(book_params)
        # associates book to user before associating a category to it
        @book = current_user.books.build(book_params)
        @book.category_id = params[:category_id]
        if @book.save
            redirect_to root_path
        else
            #render 'form'
            render plain: "Cannot save"
        end
    end


    def edit 
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update 
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
    end

    def find_book
        @book = Book.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]

    def new 
        if !user_signed_in?
            render 'error'
        end
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        @review.book_id = @book.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @review.update(review_params)
            #redirect to the show page
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
       if @review.destroy
        redirect_to book_path(@book)
       end
    end

    private

    def review_params 
        params.require(:review).permit(:rating, :comment)
    end

        #this book is sent from the review form along with its review
    def find_book
        @book = Book.find(params[:book_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, html: {multipart: true} do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories),  :prompt => "--select category--" ) %>
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, label: "Book Description" %>
    <%= f.input :author, label: "Book author" %>
    <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h3> Edit Book </h3>

<%= simple_form_for @book, html: {multipart: true} do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, label: "Book Description" %>
    <%= f.input :author, label: "Book author" %>
    <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h3> Book index </h3>

<% if @books.count == 0 %>
        <h3> There's no book in this category </h3>
 <% else %>

 <h3> <%= params[:category] %> </h3>

 <div class="row">
<% @books.each do |book| %>
        <div class="col-md-3">
                <a href="/books/<%= book.id %>">
                    <%= image_tag book.book_img.url(:book_index), class: "book" %>
                </a>
        </div>
<% end %>
</div>

<% end %>

app/views/books/new.html.erb
<h3> Create a new book </h3>

<%= render 'form' %>

<h4> <%= link_to "Return to index", root_path %> </h4>

app/views/books/show.html.erb
<h2> Show Book </h2>

<div class="row">
    <div class="col-md-4">
            <a href="#">
                    <%= image_tag @book.book_img.url(:book_show), class: "book_show" %>
            </a>
    </div>

    <div class="col-md-8">  
            <h5> <%= @book.title %> </h5>
            <h2> Average Rating </h2>
            <div class="average-review-rating" data-score="<%= @average_review %>" ></div>
            <h5> <%= @book.author %> </h5>
            <h5> <%= @book.description %> </h5>
    </div>
</div>

<div class="row">
        <div class="col-md-4">
                <!-- this is another row to hold the reviews -->
                <!-- Right below the book image-->
                <div>
                        <!-- each book review will be iterated over here -->
                        <!-- with respect to how data are displayed in the review partial-->
                        <%= render @book.reviews %>
                </div>

                <div>
                        <%= link_to "Add A Review", new_book_review_path(@book) %>
                </div>
        </div>
</div>




<h4> <%= link_to "Return to index", root_path %> </h4>

<%  if user_signed_in? %>
    <% if @book.user_id == current_user.id %>
        <%= link_to "Edit Book", edit_book_path %>
        <%= link_to "Delete Book", book_path(@book), method: :delete, data: {confirm: "You're about to delete this book"} %>
    <% end %>
<% end %>


<script>
        $('.review-rating').raty({
                readOnly: true,
                score: function() {
                        return $(this).attr('data-score');
                },
                path: '/assets/'
        });
</script>

<!-- script for average rating -->
<script>
                $('.average-review-rating').raty({
                        readOnly: true,
                        path: '/assets/',
                        score: function() {
                                return $(this).attr('data-score')
                        }
                });
        </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>
    
    <nav class="navbar navbar-default">
      
      <div class="container">
        
        <div class="navbar-header">
          <%= link_to "Book Review", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li> <%= link_to "Signup", new_user_registration_path %> </li>
          <% if user_signed_in? %>
           <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
           <% else %>
           <li> <%= link_to "Sign in", new_user_session_path %> </li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, books_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>

  

    
    
            <% if user_signed_in? %>
              <li><%= link_to "Add Book", new_book_path %></li>
            <% end %>
            
          </ul>
        
      </div>

    </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

<div class="container">
    <%= yield %>
</div>
   

  </body>
</html>

app/views/reviews/_form.html.erb
<h3> Add a review to that book </h3>

<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
    <div id="rating-form">
        <label> Rating </label> <br>
    </div>
    <%= f.input :comment, label: "Comment" %>
    <%= f.submit %>
<% end %>

<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p> <%= review.comment %> </p>
    


<% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
    <%= link_to "Edit Review" , edit_book_review_path(review.book, review) %>
    <%= link_to "Delete Review", book_review_path(review.book, review), method: :delete, data: {confirm: "Delete Review ?"} %>
<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h3> Edit review </h3>

<%= simple_form_for([@book, @review]) do |f| %>
<div id="rating-form">
    <label> Rating </label> <br>
</div>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

<script>
        $('#rating-form').raty({
            path: '/assets/',
            scoreName: 'review[rating]'
        });
    </script>

app/views/reviews/error.html.erb
<h3> Please sign in to add a review </h3>

app/views/reviews/new.html.erb
<%= render 'form' %>